# This is a basic workflow to help you get started with Actions

name: CI-Build

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in
# parallel
jobs:
  ubuntu:
    uses: ./.github/workflows/ubuntu.yml
    secrets: inherit

  linux:
    uses: ./.github/workflows/linux.yml
    secrets: inherit

